apiVersion: apps/v1
kind: Deployment
metadata:
  name: keila
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keila
  template:
    metadata:
      labels:
        app: keila
    spec:
      containers:
      - name: keila
        image: pentacent/keila:latest
        ports:
        - containerPort: 4000
        env:
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: keila-secrets
              key: SECRET_KEY_BASE
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: keila-secrets
              key: DB_URL
        - name: URL_HOST
          valueFrom:
            configMapKeyRef:
              name: keila-config
              key: URL_HOST
        - name: MAILER_SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: keila-config
              key: MAILER_SMTP_HOST
        - name: MAILER_SMTP_USER
          valueFrom:
            secretKeyRef:
              name: keila-secrets
              key: MAILER_SMTP_USER
        - name: MAILER_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keila-secrets
              key: MAILER_SMTP_PASSWORD