apiVersion: v1
kind: Secret
metadata:
  name: keila-secrets
type: Opaque
stringData:
  SECRET_KEY_BASE: "your-secret-key"
  DB_URL: "postgres://username:password@your-rds-instance:5432/keila"
  MAILER_SMTP_USER: "your-smtp-user"
  MAILER_SMTP_PASSWORD: "your-smtp-password"