name: 'Setup S3 Bucket and DynamoDB for Terraform State'

on:
  workflow_dispatch:

jobs:
  setup_terraform_backend:
    name: 'Create S3 Bucket and DynamoDB Table'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.TF_VAR_region }} 
      BUCKET_NAME: ${{ secrets.TF_VAR_backend_bucket }} 
      TABLE_NAME: ${{ secrets.TF_VAR_backend_key_table }} 

    steps:
    - name: Create S3 bucket
      run: |
        aws s3api create-bucket --bucket $BUCKET_NAME --region $AWS_REGION --create-bucket-configuration LocationConstraint=$AWS_REGION
        aws s3api put-bucket-versioning --bucket $BUCKET_NAME --versioning-configuration Status=Enabled
        aws s3api put-bucket-encryption --bucket $BUCKET_NAME --server-side-encryption-configuration '{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}'

    - name: Create DynamoDB table
      run: |
        aws dynamodb create-table \
          --table-name $TABLE_NAME \
          --attribute-definitions AttributeName=LockID,AttributeType=S \
          --key-schema AttributeName=LockID,KeyType=HASH \
          --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5