name: 'Deploy branch main'

on:
  workflow_dispatch:
  

jobs:
  apply:
    name: 'Apply Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra/terraform
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_KEY}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v4

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Apply
      run: terraform apply -auto-approve